apiVersion: apps/v1
kind: Deployment
metadata:
  name: duckeye
  namespace: knative-discovery
  labels:
    app: duckeye
spec:
  replicas: 1
  template:
    metadata:
      name: duckeye
      labels:
        app: duckeye
    spec:
      serviceAccountName: controller
      securityContext:
        runAsNonRoot: true
      containers:
        - name: duckeye
          image: ko://github.com/pierdipi/duckeye/cmd/duckeye
          imagePullPolicy: IfNotPresent
          env:
            - name: SYSTEM_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: PORT
              value: '8080'
      restartPolicy: Always
  selector:
    matchLabels:
      app: duckeye
---
apiVersion: v1
kind: Service
metadata:
  name: duckeye
  namespace: knative-discovery
spec:
  selector:
    app: duckeye
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
